### ISSUE TITLE
Frontend unresponsive after load on macos

### ISSUE THREAD

**Issue by sadrian80** [Calderis/Coloris#1]
Hello

I just downloaded and installed Coloris. The machine is macOS 10.13.2 stock.
$PATH is set correctly and ArgyllCMS works. NodeJS is installed properly.
I checked everything twice.

When started, the frontend shows up but is completely unresponsive. The word "preview" is wirtten in black below the window-controls.

Can you please advice me howto troubleshoot this?

**Comment by Calderis** [comment]
Hi @sadrian80 !
Thanks a lot for your interest in Coloris!

I'm sorry for the issue on MacOS, we've identified it recently as well but since we are working hard on making a professional version of Coloris (a second on so) we closed and stop support on the first version. 

I did not see you issue before because I wasn't prepared to see one ^^'. Sorry for the delay though...

So for the time being, Coloris can't be downloaded at all, wait a little more and subscribe to our newsletter to be informed of when does Coloris 2 will be ready : http://www.coloris-app.fr/downloads-closed/

You still can contact us by mail http://www.coloris-app.fr/contact-us/ we are way more reactive this way =) !
